name: thbenv
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - scikit-image
  - geopandas
  - psycopg2
  - pip
  - pip:
    - bcdata
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5434
  PGDATABASE: thb
  PGOGR: 'host=localhost user=postgres dbname=thb password=postgres port=5434'
