name: thbenv
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - scikit-image
  - geopandas
  - psycopg2
  - pip
  - pip:
    - bcdata
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5434
  PGDATABASE: thb
  DATABASE_URL: postgresql://postgres@localhost:5434/thb
